language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

before_install:
  - gem install cocoapods --no-ri --no-rdoc
  - cd Example

script:
  - xctool -workspace InstallrCheckerDemo.xcworkspace -scheme InstallrCheckerDemo -sdk iphonesimulator build ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO
